services:
  oracle:
    image: gvenzl/oracle-xe:latest
    container_name: oracle-db
    ports:
      - "1521:1521" 
      - "5500:5500"  
    environment:
      ORACLE_PASSWORD: mysecurepassword
      APP_USER: myuser    
      APP_USER_PASSWORD: userpassword
      ORACLE_DATABASE: mydatabase        
    volumes:
      - oracle_data:/opt/oracle/oradata 

volumes:
  oracle_data:
